#!/bin/bash +x

# libraries
source util.sh;
source config.sh
source logging.sh;
source options.sh;
source file_options.sh;
source vars-options.sh;
source node-options.sh
#source package-options.sh;

process_line "$@";